# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Calculus Applets
tagline:             'Some wicked awesome GeoGebra applets!'
description:         'Something clever here.'
url:                 'http://dcernst.github.io'
baseurl:             '/CalculusApplets'
paginate:            10

# About/contact
author:
  name:              Dana C. Ernst and Hannah Prawzinsky
  url:               https://twitter.com/danaernst
  email:             dana@danaernst.com

# Custom vars
version:             1.0.0
